version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

  backend:
    build: ./ecommerce-platform
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./ecommerce-platform:/app
      - ./ecommerce-platform/uploads:/app/uploads
    depends_on:
      - db
    env_file:
      - ./ecommerce-platform/.env
    command: yarn start:dev
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge
